language: cpp

sudo: false

os:
  - linux

language: cpp
git:
  depth: 30
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - python
    - freeglut3-dev
    - libxmu-dev
    - libxi-dev
    - libpng-dev
    - libjpeg-dev
    - libxxf86vm1
    - libxxf86vm-dev
    - libxi-dev
    - libxrandr-dev
    - mesa-common-dev
    - mesa-utils
    - libgl1-mesa-dev
    - libglapi-mesa
    - libgtk-3-dev
    - byacc
    - gettext
    
cache:
  apt: true
  directories:
  - $HOME/wxWidgets-install
  - $HOME/boost-install
  - $HOME/swig-install

notifications:
  email:
     recipients:
       - "i-simpa@ifsttar.fr"

before_install:
  - ./ci/travis/${TRAVIS_OS_NAME}/before_install.sh

install:
  - ./ci/travis/${TRAVIS_OS_NAME}/install.sh

before_script:
  - ./ci/travis/${TRAVIS_OS_NAME}/before_script.sh

script:
  - ./ci/travis/${TRAVIS_OS_NAME}/script.sh

after_script:
  - ./ci/travis/${TRAVIS_OS_NAME}/after_script.sh
