# SPDX-License-Identifier: LGPL-2.1-or-later
# ***************************************************************************
# *                                                                         *
# *   Copyright (c) 2023 0penBrain.                                         *
# *                                                                         *
# *   This file is part of ISIMPA.                                         *
# *                                                                         *
# *   ISIMPA is free software: you can redistribute it and/or modify it    *
# *   under the terms of the GNU Lesser General Public License as           *
# *   published by the Free Software Foundation, either version 2.1 of the  *
# *   License, or (at your option) any later version.                       *
# *                                                                         *
# *   ISIMPA is distributed in the hope that it will be useful, but        *
# *   WITHOUT ANY WARRANTY; without even the implied warranty of            *
# *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU      *
# *   Lesser General Public License for more details.                       *
# *                                                                         *
# *   You should have received a copy of the GNU Lesser General Public      *
# *   License along with ISIMPA. If not, see                               *
# *   <https://www.gnu.org/licenses/>.                                      *
# *                                                                         *
# ***************************************************************************

# This is the master workflow for CI of I-SIMPA.
# It (only) aims at properly organizing the sub-workflows.

name: I-SIMPA main CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: IS-CI-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  Prepare:
    uses: ./.github/workflows/sub_prepare.yml
    with:
      artifactBasename: Prepare-${{ github.run_id }}

  Linux:
    needs: [Prepare]
    uses: ./.github/workflows/sub_buildLinux.yml
    with:
      artifactBasename: Linux-${{ github.run_id }}

  Windows:
    needs: [Prepare]
    uses: ./.github/workflows/sub_buildWindows.yml
    with:
      artifactBasename: Windows-${{ github.run_id }}

  MacOS:
    needs: [Prepare]
    uses: ./.github/workflows/sub_buildMacOS.yml
    with:
      artifactBasename: MacOS-${{ github.run_id }}

  WrapUp:
    needs: [
        Prepare,
        Linux,
        Windows,
        MacOS
      ]
    if: always()
    uses: ./.github/workflows/sub_wrapup.yml
    with:
      previousSteps: ${{ toJSON(needs) }}
